export const devices = [
    {
      manufacturer: 'Apple',
      device: 'iPad 2',
      screenSize: '9.7 inch',
      resolution: '768x1024',
      density: '132 ppi',
      os: 'iOS',
      osVersion: '8.1.1',
      simType: 'Micro-SIM',
      date: 'Aug.17',
      type: 'Tablet',
      webViewVer: 'WKWebView',
      avatar: 'http://www.mobilebulgaria.com/uploads/products/2/2014/11/270x_19087.jpg',
      isAvailable: true,
      booker: '',
    },
    {
      manufacturer: 'Apple',
      device: 'iPhone 6 Plus',
      screenSize: '5.5 inch',
      resolution: '1920x1080',
      density: '401 ppi',
      os: 'iOS',
      osVersion: '11.2',
      simType: 'Nano-SIM',
      date: 'Aug.17',
      type: 'Phone',
      webViewVer: 'WKWebView',
      avatar: 'http://www.mobilebulgaria.com/uploads/products/mobiles/3/270x_18179.jpg',
      isAvailable: true,
      booker: '',
    },
    {
      manufacturer: 'Apple',
      device: 'iPad Air 1',
      screenSize: '9.7 inch',
      resolution: '1536x2048',
      density: '264 ppi',
      os: 'iOS',
      osVersion: '11.2',
      simType: 'Nano-SIM',
      date: 'Aug.17',
      type: 'Tablet',
      webViewVer: 'WKWebView',
      avatar: 'http://data2020.co.uk/image/cache/catalog/Phones/iPhones/SAPPIPAAW16GSB_l[1]-500x500.jpg',
      isAvailable: true,
      booker: '',
    },
    {
      manufacturer: 'Apple',
      device: 'iPhone SE',
      screenSize: '4 inch',
      resolution: '1136x640',
      density: '326 ppi',
      os: 'iOS',
      osVersion: '10.02.01',
      simType: 'Nano-SIM',
      date: 'Aug.17',
      type: 'Phone',
      webViewVer: 'WKWebView',
      avatar: 'http://www.mobilebulgaria.com/uploads/products/1/2016/03/270x_35624.jpg',
      isAvailable: true,
      booker: '',
    },
    {
      manufacturer: 'Apple',
      device: 'iPad mini 4',
      screenSize: '7.9 inch',
      resolution: '2048x1536',
      density: '326 ppi',
      os: 'iOS',
      osVersion: '11',
      simType: 'Nano-SIM',
      date: 'Aug.17',
      type: 'Tablet',
      webViewVer: 'WKWebView',
      avatar: 'http://www.mobilebulgaria.com/uploads/products/2/2015/12/270x_34592.jpg',
      isAvailable: true,
      booker: '',
    },
    {
      manufacturer: 'Apple',
      device: 'iPad Pro 9.7 32G Cellular',
      screenSize: '9.7 inch',
      resolution: '2048x1536',
      density: '264 ppi',
      os: 'iOS',
      osVersion: '11.1.1',
      simType: 'Nano-SIM',
      date: 'Jul.17',
      type: 'Tablet',
      webViewVer: 'WKWebView',
      avatar: 'http://www.mobilebulgaria.com/uploads/products/2/2016/10/270x_37859.jpg',
      isAvailable: true,
      booker: '',
    },
    {
      manufacturer: 'Apple',
      device: 'iPhone 6',
      screenSize: '4.7 inch',
      resolution: '750x1334',
      density: '326 ppi',
      os: 'iOS',
      osVersion: '10.03.02',
      simType: 'Nano-SIM',
      date: 'Nov.16',
      type: 'Phone',
      webViewVer: 'WKWebView',
      avatar: 'http://www.mobilebulgaria.com/uploads/products/mobiles/3/270x_18180.jpg',
      isAvailable: true,
      booker: '',
    },
    {
      manufacturer: 'Apple',
      device: 'iPhone 7',
      screenSize: '4.7 inch',
      resolution: '1334x750',
      density: '326 ppi',
      os: 'iOS',
      osVersion: '11',
      simType: 'Nano-SIM',
      date: 'Jul.17',
      type: 'Phone',
      webViewVer: 'WKWebView',
      avatar: 'http://www.mobilebulgaria.com/uploads/products/1/2016/09/270x_37614.jpg',
      isAvailable: true,
      booker: '',
    },
    {
      manufacturer: 'Samsung',
      device: 'S7 Edge',
      screenSize: '5.5 inch',
      resolution: '1440x2560',
      density: '534 ppi',
      os: 'Android',
      osVersion: 'Nougat',
      simType: 'Nano-SIM',
      date: 'Nov.16',
      type: 'Phone',
      webViewVer: 'WebView is built into Chrome v62.0.3202',
      avatar: 'http://www.mobilebulgaria.com/uploads/products/1/2016/02/270x_35157.jpg',
      isAvailable: true,
      booker: '',
    },
    {
      manufacturer: 'Samsung',
      device: 'Galaxy S8 Plus',
      screenSize: '5.8 inch',
      resolution: '1440x2960',
      density: '570 ppi',
      os: 'Android',
      osVersion: 'Nougat',
      simType: 'Nano-SIM',
      date: 'Jul.17',
      type: 'Phone',
      webViewVer: 'WebView is built into Chrome v62.0.3202',
      avatar: 'http://www.mobilebulgaria.com/uploads/products/1/2017/03/270x_39870.jpg',
      isAvailable: false,
      booker: 'GoodFellas',
    },
    {
      manufacturer: 'Samsung',
      device: 'Galaxy S5',
      screenSize: '5.1 inch',
      resolution: '1080x1920',
      density: '432 ppi',
      os: 'Android',
      osVersion: 'Kitkat 4.4.4',
      simType: 'Micro-SIM',
      date: 'Jul.15',
      type: 'Phone',
      webViewVer: 'WebView v33.0.0.0 upgrades only with OS',
      avatar: 'http://www.mobilebulgaria.com/uploads/products/1/2015/09/270x_31217.jpg',
      isAvailable: false,
      booker: 'GoodFellas',
    },
    {
      manufacturer: 'Samsung',
      device: 'Galaxy Tab A 10.1',
      screenSize: '10.1 inch',
      resolution: '1200x1920',
      density: '224 ppi',
      os: 'Android',
      osVersion: 'Marshmallow 6.0.1',
      simType: 'Micro-SIM',
      date: 'Nov.16',
      type: 'Tablet',
      webViewVer: 'WebView is built into Chrome v62.0.3202',
      avatar: 'https://images-na.ssl-images-amazon.com/images/I/81tJW-wwHDL._SY550_.jpg',
      isAvailable: false,
      booker: 'GoodFellas',
    },
    {
      manufacturer: 'Samsung',
      device: 'Galaxy Tab S 8.4',
      screenSize: '8.4 inch',
      resolution: '1600x2560',
      density: '359 ppi',
      os: 'Android',
      osVersion: 'Marshmallow 6.0.1',
      simType: 'Micro-SIM',
      date: 'Jan.18',
      type: 'Tablet',
      webViewVer: 'WebView is built into Chrome v62.0.3202',
      avatar: 'https://images-na.ssl-images-amazon.com/images/I/81tJW-wwHDL._SY550_.jpg',
      isAvailable: false,
      booker: 'GoodFellas',
    },
    {
      manufacturer: 'Sony',
      device: 'Xperia Z3 Compact',
      screenSize: '4.6 inch',
      resolution: '1280x720',
      density: '319 ppi',
      os: 'Android',
      osVersion: 'Marshmallow 6.0.1',
      simType: 'Nano-SIM',
      date: 'Aug.17',
      type: 'Phone',
      webViewVer: 'WebView is built into Chrome v62.0.3202',
      avatar: 'http://www.mobilebulgaria.com/uploads/products/mobiles/3/270x_18208.jpg',
      isAvailable: false,
      booker: 'GoodFellas',
    },
    {
      manufacturer: 'Google',
      device: 'Nexus 6',
      screenSize: '5.96 inch',
      resolution: '1440x2560',
      density: '493 ppi',
      os: 'Android',
      osVersion: 'Marshmallow 6.0.1',
      simType: 'Nano-SIM',
      date: 'Aug.17',
      type: 'Phone',
      webViewVer: 'Android System WebView v62.0.3202',
      avatar: 'http://www.mobilebulgaria.com/uploads/products/mobiles/3/270x_18586.jpg',
      isAvailable: false,
      booker: 'GoodFellas',
    },
    {
      manufacturer: 'Google',
      device: 'Nexus 7',
      screenSize: '7 inch',
      resolution: '1280x800',
      density: '216 ppi',
      os: 'Android',
      osVersion: 'Lollipop 5.1.1',
      simType: 'Nano-SIM',
      date: 'Aug.17',
      type: 'Tablet',
      webViewVer: 'Android System WebView v62.0.3202',
      avatar: 'http://www.mobilebulgaria.com/uploads/products/tablets/10/270x_2621.jpg',
      isAvailable: false,
      booker: 'GoodFellas',
    },
    {
      manufacturer: 'LG',
      device: 'G5 SE',
      screenSize: '5.3 inch',
      resolution: '1140x2560',
      density: '554 ppi',
      os: 'Android',
      osVersion: 'Marshmallow 6.0.1',
      simType: 'Micro-SIM',
      date: 'Aug.17',
      type: 'Phone',
      webViewVer: 'Android System WebView v62.0.3202',
      avatar: 'http://www.mobilebulgaria.com/uploads/products/1/2016/10/270x_37963.jpg',
      isAvailable: false,
      booker: 'GoodFellas',
    },
    {
      manufacturer: 'Oneplus',
      device: '3T',
      screenSize: '5.5 inch',
      resolution: '1080x1920',
      density: '401 ppi',
      os: 'Android',
      osVersion: 'Oreo 8.0.0',
      simType: 'Nano-SIM',
      date: 'Jul.17',
      type: 'Phone',
      webViewVer: 'Android System WebView v62.0.3202',
      avatar: 'http://www.mobilebulgaria.com/uploads/products/1/2017/07/270x_39209.jpg',
      isAvailable: false,
      booker: 'GoodFellas',
    },
  ]